/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Daemon client module.
 */
module org.foodpanda.daemon {
  exports org.foodpanda.daemon;

  requires org.foodpanda.persist;
  requires org.foodpanda.domain;

  requires java.rmi;

  provides org.tentackle.common.ModuleHook with org.foodpanda.daemon.service.Hook;
}
