/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Common stuff not belonging to a certain abstraction level.
 */
module org.foodpanda.common {
  exports org.foodpanda.common;

  requires transitive org.tentackle.pdo;

  provides org.tentackle.common.ModuleHook with org.foodpanda.common.service.Hook;
}
