/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.server;

/**
 * Test constants.
 */
public class TestConstants {

  /** test group to initialize the CI database. */
  public static final String GROUP_INITDB = "initdb";

}
