/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Domain logic implementation module.
 */
module org.foodpanda.domain {
  exports org.foodpanda.domain;
  exports org.foodpanda.domain.md;
  exports org.foodpanda.domain.td;

  requires transitive org.foodpanda.pdo;

  requires transitive org.tentackle.domain;

  provides org.tentackle.common.ModuleHook with org.foodpanda.domain.service.Hook;
}
