/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui;

import org.tentackle.fx.DefaultImageProvider;
import org.tentackle.fx.ImageProviderService;

/**
 * Application specific image provider.
 */
@ImageProviderService(foodpandaImageProvider.REALM)
public class foodpandaImageProvider extends DefaultImageProvider {

  /**
   * The application's image realm.
   */
  public static final String REALM = "foodpanda";

}
