/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui;


/**
 * GUI constants.
 */
public class GuiConstants {

  /**
   * The application specific menu items group.
   */
  public static final String ITEM_GROUP = "foodpanda";

  private GuiConstants() {}
}
