/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.common;

/**
 * Application specific constants.
 */
public class Constants {

  /**
   * Number pool realm of foodpanda.
   */
  public static final String POOL_REALM = "foodpanda";

  private Constants() {}
}
