/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.common;

import org.tentackle.bind.Bindable;
import org.tentackle.common.Service;
import org.tentackle.common.ServiceFactory;
import org.tentackle.prefs.CompositePreferences;
import org.tentackle.prefs.PersistedPreferencesFactory;


interface foodpandaPreferencesHolder {
  foodpandaPreferences INSTANCE = ServiceFactory.createService(foodpandaPreferences.class);
}

/**
 * Preferences for foodpanda.
 */
@Service(foodpandaPreferences.class)    // defaults to self
public class foodpandaPreferences extends CompositePreferences {


  /** online help prefix. */
  public static final String HELP_URL = "helpURL";



  public foodpandaPreferences() {
    super(PersistedPreferencesFactory.getInstance().isSystemOnly());
  }

  /**
   * The singleton.
   *
   * @return the singleton
   */
  public static foodpandaPreferences getInstance() {
    return foodpandaPreferencesHolder.INSTANCE;
  }



  @Bindable
  public void setHelpUrl(String val) {
    setString(HELP_URL, val);
  }

  @Bindable
  public String getHelpUrl() {
    return getString(HELP_URL);
  }

}
