/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.common;

import org.tentackle.session.DefaultSessionInfo;

import java.io.Serial;
import java.util.Properties;

/**
 * Application specific session info.
 */
public class foodpandaSessionInfo extends DefaultSessionInfo {

  @Serial
  private static final long serialVersionUID = 1L;


  /**
   * Create session info from a username, password and
   * property file holding the connection parameters.
   *
   * @param username is the name of the user, null if {@code System.getProperty("user.name")}
   * @param password is the password, null if none
   * @param propertiesName name of the db-properties, null if {@code "Db"}
   */
  public foodpandaSessionInfo(String username, char[] password, String propertiesName) {
    super(username, password, propertiesName);
  }

  /**
   * Create session info from a property file holding the connection parameters.
   *
   * @param propertiesName name of the db-properties, null if {@code "backend"}
   */
  public foodpandaSessionInfo(String propertiesName) {
    super(propertiesName);
  }

  /**
   * Create session from a properties object.
   *
   * @param properties the properties
   */
  public foodpandaSessionInfo(Properties properties)  {
    super(properties);
  }

  /**
   * Create session info from the default property file {@code "backend"}.
   */
  public foodpandaSessionInfo() {
    super();
  }

  @Override
  public void setUserName(String userName) {
    super.setUserName(userName == null ? null : userName.toUpperCase());    // usernames are uppercase only
  }
}
