/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Persistence implementation module.
 */
module org.foodpanda.persist {
  exports org.foodpanda.persist;
  exports org.foodpanda.persist.md;
  exports org.foodpanda.persist.md.rmi;
  exports org.foodpanda.persist.rmi;
  exports org.foodpanda.persist.td;
  exports org.foodpanda.persist.td.rmi;

  requires transitive org.foodpanda.pdo;

  requires transitive org.tentackle.persistence;

  requires java.rmi;

  provides org.tentackle.common.ModuleHook with org.foodpanda.persist.service.Hook;
}
