/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Persistent Domain Object (PDO) module.
 */
module org.foodpanda.pdo {
  exports org.foodpanda.pdo;
  exports org.foodpanda.pdo.md;
  exports org.foodpanda.pdo.md.domain;
  exports org.foodpanda.pdo.md.persist;
  exports org.foodpanda.pdo.security;
  exports org.foodpanda.pdo.td;
  exports org.foodpanda.pdo.td.domain;
  exports org.foodpanda.pdo.td.persist;

  requires transitive org.foodpanda.common;

  provides org.tentackle.common.ModuleHook with org.foodpanda.pdo.service.Hook;
}
