/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbConnection;

/**
 * Interface for the appliction specific connection.
 */
public interface foodpandaConnection extends RemoteDbConnection {

}
