/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.persist.rmi;

import org.foodpanda.pdo.foodpandaRemoteSession;

import org.tentackle.dbms.rmi.RemoteDbSession;
import org.tentackle.persist.PdoRemoteSessionAdapter;

/**
 * Application specific remote session adapter.
 */
public class foodpandaRemoteSessionAdapter extends PdoRemoteSessionAdapter implements foodpandaRemoteSession {

  public foodpandaRemoteSessionAdapter(RemoteDbSession rs) {
    super(rs);
  }

  @Override
  public foodpandaRemoteDbSession getRemoteDbSession() {
    return (foodpandaRemoteDbSession) super.getRemoteDbSession();
  }

}

