/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbSession;

/**
 * Interface for the remote session.
 */
public interface foodpandaRemoteDbSession extends RemoteDbSession {

}