/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Desktop FX client module.
 */
module org.foodpanda.client {
  exports org.foodpanda.client;

  requires org.foodpanda.gui;
  requires org.foodpanda.persist;
  requires org.foodpanda.domain;

  requires org.tentackle.fx.rdc;
  requires org.tentackle.fx.rdc.update;

  requires javafx.graphics;
  requires java.prefs;

  provides org.tentackle.common.ModuleHook with org.foodpanda.client.service.Hook;
}
