/*
 * foodpanda generated by tentackle-project-archetype.
 */

/**
 * Middle tier server module.
 */
module org.foodpanda.server {
  exports org.foodpanda.server;
  exports org.foodpanda.server.rmi;

  requires org.foodpanda.persist;
  requires org.foodpanda.domain;

  requires java.rmi;
  requires java.prefs;

  requires org.tentackle.update;

  provides org.tentackle.common.ModuleHook with org.foodpanda.server.service.Hook;
}