/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.pdo.md.domain;

import org.foodpanda.pdo.md.OrgUnit;

import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for OrgUnit.
 *
 * @param <T> the OrgUnit type
 */
public interface OrgUnitDomain<T extends OrgUnit<T>> extends DomainObject<T> {

}
