/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.pdo.md.domain;

import org.foodpanda.pdo.md.UserGroup;

/**
 * Domain interface for UserGroup.
 */
public interface UserGroupDomain extends OrgUnitDomain<UserGroup> {

}
