/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.pdo.md.domain;

import org.foodpanda.pdo.md.User;

/**
 * Domain interface for User.
 */
public interface UserDomain extends OrgUnitDomain<User> {

}
