/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.pdo.md.domain;

import org.foodpanda.pdo.md.User2Group;

import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for User2Group.
 */
public interface User2GroupDomain extends DomainObject<User2Group> {

}
