/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui.prefs;

import org.foodpanda.common.foodpandaPreferences;

import org.tentackle.bind.Bindable;
import org.tentackle.fx.AbstractFxController;

/**
 * Base controller class for a preferences tab.
 */
public abstract class AbstractPreferencesTabController extends AbstractFxController {

  @Bindable
  public foodpandaPreferences getPref() {
    return foodpandaPreferences.getInstance();
  }

}
