/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.persist.md.rmi;

import org.foodpanda.pdo.MasterData;
import org.foodpanda.persist.AbstractPersistentMasterData;

import org.tentackle.persist.rmi.AbstractPersistentObjectRemoteDelegate;

/**
 * Base interface for master data remote delegates.
 */
public interface AbstractPersistentMasterDataRemoteDelegate<T extends MasterData<T>,
                                                            P extends AbstractPersistentMasterData<T,P>>
       extends AbstractPersistentObjectRemoteDelegate<T,P> {

}

