/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.persist.md.rmi;

import org.foodpanda.pdo.md.UserGroup;
import org.foodpanda.persist.md.UserGroupPersistenceImpl;


/**
 * Remote delegate for {@link UserGroupPersistenceImpl}.
 */
public interface UserGroupRemoteDelegate
       extends OrgUnitRemoteDelegate<UserGroup,UserGroupPersistenceImpl> {

  // @wurblet inclrmi Include --missingok .$classname/methods

//<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi


//</editor-fold>//GEN-END:inclrmi


}
