/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui;

import org.tentackle.test.fx.rdc.ControllerTest;

/**
 * Tests all FX controllers.
 */
public class TestControllers extends ControllerTest {}
