/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui;

import org.tentackle.test.fx.rdc.TableConfigurationProviderTest;

/**
 * Tests all TableConfigurationProviders.
 */
public class TestTableConfigurationProviders extends TableConfigurationProviderTest {}
