/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.gui;

import org.tentackle.test.fx.rdc.GuiProviderTest;

/**
 * Tests all GuiProviders.
 */
public class TestGuiProviders extends GuiProviderTest {}
