/*
 * foodpanda generated by tentackle-project-archetype.
 */

package org.foodpanda.pdo;

import org.tentackle.pdo.PersistentDomainObject;

/**
 * Common PDO interface for masterdata.
 *
 * @param <T> the PDO type
 */
public interface MasterData<T extends PersistentDomainObject<T>> extends PersistentDomainObject<T> {

}
